version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-backend:latest
#    Для масштабирования нужно убрать имя контейнера
#    container_name: sausage-backend
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      REPORT_PATH: ./
      VIRTUAL_HOST: s_host
    networks:
      - sausage-store


  report:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-report:latest
    container_name: sausage-report
    environment:
       DB: ${MONGO}
       PORT: 8081
    networks:
      - sausage-store


  nginx:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-nginx:latest
    container_name: sausage-nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=s_host
    networks:
      - sausage-store

networks:
  sausage-store: