version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-backend:latest
    container_name: sausage-backend
    environment:
      # Переменные из application.properties можно заменить переменными окружения
#      SPRING_DATASOURCE_USERNAME: ${DBLOGIN}
#      SPRING_DATASOURCE_PASSWORD: ${DBPASS}
      SPRING_DATASOURCE_USERNAME: artamokhin1
      SPRING_DATASOURCE_PASSWORD: ***REMOVED***
      SPRING_DATASOURCE_URL: jdbc:postgresql://***REMOVED***
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage-store


  report:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-report:1.0.0
    container_name: sausage-report
    build:
      context: report
      dockerfile: Dockerfile
    environment:
#      DB: ${MONGO_DATA}
       DB: mongodb://artamokhin1:***REMOVED***@rc1a-ftsq82uol4t7mcoq.mdb.yandexcloud.net:27018/artamokhin1?tls=true
       PORT: 8080
    networks:
      - sausage-store


  frontend:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-frontend:latest
    container_name: sausage-frontend
    ports:
      - "80:80"
    networks:
      - sausage-store

networks:
  sausage-store: