version: "3.4"

services:
  backend-blue:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-backend:latest
#    Для масштабирования нужно убрать имя контейнера
    container_name: blue
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      REPORT_PATH: ./
      VIRTUAL_HOST: sausage
#    healthcheck:
#      test: curl --fail -s http://localhost:8080/actuator/health
#      interval: 30s
#      timeout: 10s
#      start_period: 20s
#      retries: 6
    networks:
      - sausage-store

  backend-green:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-backend:latest
#    Для масштабирования нужно убрать имя контейнера
    container_name: green
    environment:
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}
      REPORT_PATH: ./
      VIRTUAL_HOST: sausage
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 6
    networks:
      - sausage-store


  report:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-report:latest
    container_name: sausage-report
    environment:
       DB: ${SPRING_DATA_MONGODB_URI}
       PORT: 8080
    networks:
      - sausage-store


  nginx:
    image: gitlab.praktikum-services.ru:5050/std-012-056/sausage-store/sausage-nginx:latest
    container_name: sausage-nginx
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: sausage
    networks:
      - sausage-store

networks:
  sausage-store: